### ISSUE TITLE
Image with placeholder and known size is replaced by a scaled placeholder

### ISSUE THREAD

**Issue by Adonai** [noties/Markwon#115] opened 2019-04-13 09:15 UTC
* **Markwon version**: _3.0.0_

1. Please specify expected/actual behavior

Expected: I should see scaled image once it's loaded.
Actual: I see scaled placeholder.

![image](https://user-images.githubusercontent.com/863272/56077404-8530b800-5de4-11e9-8e14-43d032951017.png)

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

* Add standard image plugin
* Configure placeholder for the images
* Add image with `img` tag, with width and height
* Refresh text view a couple of times

I'm not sure, it's quite complex scenario, but loading goes like this:

1. `AsyncDrawable#setResult` is called with a placeholder - understandable, that's all we have for now
2. `TextView#onDraw` chimes in and populates our `AsyncDrawable` with size via `AsyncDrawable#initWithKnownDimensions`.
3. `AsyncDrawableScheduler.DrawableCallbackImpl` detects size change and reapplies view text - **note we still got the placeholder, but it's scaled now**
4. Image gets loaded
5. `AsyncDrawable#setResult` is called, now with actual image. **But dimensions didn't change as we already have them applied in step 2!** Hence `DrawableCallbackImpl` only calls `view.postInvalidate()` which (as you already know) is notorious for its unability to update embedded drawables.
6. All the user sees is scaled placeholder.

**Comment by noties** [comment] 2019-04-15 10:21
Hello @Adonai !

Thank you for such detailed issue 🙌 !

I can confirm that placeholder is not updated to a loaded image. 

Placeholder is scaled because your image has size specified (most likely via html). Unfortunately there is no way to make a placeholder size independent in such case. Maybe we actually do not need it. As, for example html, will behave like this also (and most of Android image-loaders follow the lead). This can be fixed by using a simple drawable wrapper:

```java
public class PlaceholderDrawable extends Drawable {

    @Nullable
    private final Paint backgroundPaint;

    private final Drawable drawable;

    private float left;
    private float top;

    public PlaceholderDrawable(@ColorInt int backgroundColor, @NonNull Drawable drawable) {
        this.drawable = drawable;

        // if it's transparent -> no need to draw anything
        if (backgroundColor == 0) {
            backgroundPaint = null;
        } else {
            backgroundPaint = new Paint(Paint.ANTI_ALIAS_FLAG);
            backgroundPaint.setStyle(Paint.Style.FILL);
            backgroundPaint.setColor(backgroundColor);
        }

        // it's important to have bounds for wrapped drawable
        DrawableUtils.applyIntrinsicBoundsIfEmpty(this.drawable);
    }

    @Override
    protected void onBoundsChange(Rect bounds) {
        super.onBoundsChange(bounds);

        final float w = bounds.width();
        final float h = bounds.height();

        // please note that we _assume_ that drawable is always less than possible bounds
        // if it's not always the case please consider introducing scale-down logic of your own
        final Rect rect = drawable.getBounds();
        left = (w - rect.width()) / 2.F;
        top = (h - rect.height()) / 2.F;
    }

    @Override
    public void draw(@NonNull Canvas canvas) {
        final int save = canvas.save();
        try {

            // if it's not transparent -> draw it
            if (backgroundPaint != null) {
                canvas.drawRect(getBounds(), backgroundPaint);
            }

            // center wrapped drawable
            canvas.translate(left, top);

            // and draw it
            drawable.draw(canvas);
        } finally {
            canvas.restoreToCount(save);
        }
    }

    // ###################
    // # It's important to return wrapped drawable intrinsic width & height
    // ###################

    @Override
    public int getIntrinsicWidth() {
        return drawable.getIntrinsicWidth();
    }

    @Override
    public int getIntrinsicHeight() {
        return drawable.getIntrinsicHeight();
    }

    @Override
    public void setAlpha(int alpha) {
        // no op
    }

    @Override
    public void setColorFilter(@Nullable ColorFilter colorFilter) {
        // no op
    }

    @Override
    public int getOpacity() {
        return PixelFormat.OPAQUE;
    }
}
```

As for actual change of placeholder->loaded-image, I think there is an issue in AsyncDrawable (which applied bounds for a placeholder with empty bounds). I removed this part and published a new SNAPSHOT version. Please look at it and tell me if that resolves the issue

**Comment by Adonai** [comment] 2019-04-15 20:38
I'll test it as soon as I can this week

**Comment by Adonai** [comment] 2019-04-15 21:12
I tried, but unfortunately my placeholder has bounds, 36x36, so it's another use-case.

**Comment by noties** [comment] 2019-04-16 09:24
Hello @Adonai !

I added ability to use different placeholder size. The logic is simple: if your placeholder has **non-empty** bounds, then it will be used for placeholder only. If placeholder doesn't have bounds -> current logic will be used (scaling placeholder, etc). So:

```java
.usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureImages(@NonNull AsyncDrawableLoader.Builder builder) {
        builder.placeholderDrawableProvider(new AsyncDrawableLoader.DrawableProvider() {
            @Override
            public Drawable provide() {
                final Drawable icon = context.getResources().getDrawable(R.drawable.ic_play_circle_filled_18dp_white);
                // apply intrinsic bounds, or any bounds that you want for the placeholder
                DrawableUtils.applyIntrinsicBounds(icon);
                return icon;
            }
        });
    }
})
```

I'm publishing new SNAPSHOT version

**Comment by Adonai** [comment] 2019-04-16 18:27
@noties thanks, it works this way!

**Closed** 2019-04-25 11:45 UTC
Labels: :bug: bug
