### ISSUE TITLE
Weird glitch with Tables?

### ISSUE THREAD

**Issue by KirkBushman** [noties/Markwon#245] opened 2020-05-11 16:36 UTC
* **Markwon version**: 4.3.1

Hi Noties, 
I don't know if this is a mistake on my end, or is an actual problem, but this is what I have.
Keep in mind I encounter this rarely.

this is the markwon table I'm trying to render:
```
|   Date  |  Time  |  Who   |   What  | Link |
|:--------:|:-------:|:-------:|:-------:|:-------:|
| 18th June | 7:30AM PST / 2:30PM GMT | [Gradle](https://gradle.org/) | Building Android apps with Gradle | [Link](https://reddit.com/r/androiddev/comments/c22a31/were_part_of_the_gradle_team_ask_us_anything/) |
| 20th June | 9AM PST / 4PM GMT | [Nerdery](https://www.nerdery.com/) | Remote Android working | [Link](https://www.reddit.com/r/androiddev/comments/c2vo8n/were_part_of_the_nerdery_team_ask_us_anything/) |
| 24th June | 10AM PST / 5PM GMT | [Hinge](https://hinge.co/) | General Android development / design | [Link](https://www.reddit.com/r/androiddev/comments/c4pv9q/were_part_of_the_hinge_team_ask_us_anything/) |
| 25th June | 1PM PST / 8PM GMT | [Bugsnag](https://www.bugsnag.com/) | Mobile crash reporting | [Link](https://www.reddit.com/r/androiddev/comments/c5chdo/were_part_of_the_bugsnag_team_ask_us_anything/) |
| 15th July | 11AM PST / 6PM GMT | [Pandora](https://play.google.com/store/apps/details?id=com.pandora.android) | Android dev | [Link](https://www.reddit.com/r/androiddev/comments/cdj9tn/were_part_of_the_pandora_android_team_ask_us/) |
| 16th July | 11AM PST / 6PM GMT | [Reddit](https://play.google.com/store/apps/details?id=com.reddit.frontpage) | Android dev | [Link](https://www.reddit.com/r/androiddev/comments/ce028h/were_the_team_thats_working_on_the_reddit_app_ask/) |
| 1st August | 12PM PST / 7PM GMT | Android Engineering | Android Q | [Link](https://www.reddit.com/r/androiddev/comments/ci4tdq/were_on_the_engineering_team_for_android_q_ask_us/) |
| 29th August | 8:30AM PST / 3:30PM GMT | [TomTom](https://www.tomtom.com) | Android dev | [Link](https://www.reddit.com/r/androiddev/comments/cx1xlt/we_are_part_of_the_maps_apis_sdk_team_for_tomtom/) |
```

This is my simple view: 

```
<TextView
    android:id="@+id/page"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    />
```

and this is how it comes out: 

![table-glitch](https://user-images.githubusercontent.com/20772090/81586681-2efec180-93b6-11ea-8d54-26796700b741.png)

I tried removing everything extra, but I keep getting this.
What could it be?

Thanks in advance.

**Comment by noties** [comment] 2020-05-12 08:54
Hello @KirkBushman ,

From your screenshot it seems to be an invalidation issue. Are you using markdown tables inside a `RecyclerView` or some other _special_ widget?

**Comment by KirkBushman** [comment] 2020-05-12 08:59
Nope,
standard ConstraintLayout, I've removed everything from the view to the bear minimum, trying a LinearLayout too and the same is happening.

It's inside a fragment, but I don't see that as a problem.

**Comment by noties** [comment] 2020-05-12 09:17
Can you please try your input in the sample app? [master-4.3.1](https://github.com/noties/Markwon/blob/master/sample/src/main/java/io/noties/markwon/sample/table/TableActivity.java#L68) and [develop-4.4.0-SNAPSHOT](https://github.com/noties/Markwon/blob/develop/sample/src/main/java/io/noties/markwon/sample/table/TableActivity.java#L71)

**Comment by KirkBushman** [comment] 2020-05-12 13:32
It's working in the sample app...

But wait a second, the fragment is inside a ViewPager2, that is a RecyclerView implementation.
Testing right now, but it's the only thing I haven't tested. It must be it.

**Comment by KirkBushman** [comment] 2020-05-12 15:05
It's not the RecyclerView or the Fragment or the ViewPager2.

It goes back to normal when I comment the text setter:
PrecomputedFutureTextSetterCompat

(funny enough)

**Comment by KirkBushman** [comment] 2020-05-12 15:57
If I try to add PrecomputedFutureTextSetterCompat in the sample app,
I don't get the same behaviour, so it's not a conflict of any type, between the setter and some plugins.

I feel like if appCompatTextView.getTextMetricsParamsCompat() had any difficulty getting the size of the table correctly, it would get it wrong everywhere.

So there is something it does not like but I cannot pinpoint what it is.
In my app I'm using night/day theme, material design components, androidx that could conflict with MW.

What do you think?

**Comment by KirkBushman** [comment] 2020-05-12 17:33
The outdated deps are part of the problem, upgrading to api 29 the sample + using PrecomputedFutureTextSetterCompat produces the same glitch in the sample app.

**Comment by noties** [comment] 2020-05-12 20:10
Outdated dependencies are _part of the problem_ you say? Seems to be quite the opposite as new dependencies introduce it 😉 

Anyway, what a ride. Thanks for pin-pointing the issue it will be really helpful 🙌

**Comment by noties** [comment] 2020-05-12 20:21
BTW, I still do not see any reason to use `PrecomputedFutureTextSetterCompat` as it is _still_ using synchronous `future.get()` call on the main thread. Have you tried the _regular_ `PrecomputedTextSetterCompat`, does it yield the same _glitchy_ result?

**Comment by KirkBushman** [comment] 2020-05-13 08:19
> Outdated dependencies are part of the problem you say? Seems to be quite the opposite as new dependencies introduce it :wink:

Technically true, but are doing a bamboozle there. :smile: The apps Api level will go up to support newer devices on newer releases, if the lib stays behind, you are not testing for behaviour changes.

> Have you tried the regular PrecomputedTextSetterCompat, does it yield the same glitchy result?

Using it a lot inside recyclerViews, it causes loads of problems with callbacks, that PrecomputedFutureTextSetterCompat does not yields.
Fixing this, should solve it for me.

Trying PrecomputedTextSetterCompat on api 29, I guess, I see sort of a race condition, cause I saw the glitch the first time and after that it's ok...

**Comment by aggarwalpulkit596** [comment] 2020-05-17 05:53
@noties any probable fix for this one ?

**Comment by noties** [comment] 2020-05-18 15:43
@aggarwalpulkit596 do not use `PrecomputedTextSetterCompat` and `PrecomputedFutureTextSetterCompat` 😉

**Comment by aggarwalpulkit596** [comment] 2020-05-18 15:45
I haven't use either of them still getting the issue

**Comment by noties** [comment] 2020-05-18 15:46
@aggarwalpulkit596 is your markdown inside a `RecyclerView`?

**Comment by aggarwalpulkit596** [comment] 2020-05-18 15:49
@noties nope 
https://github.com/coding-blocks/CBOnlineApp/blob/04b6e39f1878ded336425bf1dd48804984002665/app/src/main/res/layout/activity_course.xml#L193
https://github.com/coding-blocks/CBOnlineApp/blob/04b6e39f1878ded336425bf1dd48804984002665/app/src/main/java/com/codingblocks/cbonlineapp/course/CourseActivity.kt#L146

**Comment by noties** [comment] 2020-05-18 16:06
@aggarwalpulkit596 this expands the area of this issue quite a bit. Were tables working with `28` compilation target?

**Comment by aggarwalpulkit596** [comment] 2020-05-18 16:09
Yes they are working on 28 but not with 29

**Comment by aggarwalpulkit596** [comment] 2020-05-18 16:11
And yes it happens for the intial rendering but when i open a bottomsheet and close that it's get back to normal so some issue for the intial rendering

**Comment by noties** [comment] 2020-05-19 10:00
@aggarwalpulkit596 @KirkBushman ,

Changing compile and target SDK to `29` and build tools to `29.0.3` has no effect for me. Tables are rendered as expected both in a `RecyclerView` and not, with precomputed text setter or not. It seems to be an error somewhere else. Can you please provide an input that I can reproduce?

**Comment by KirkBushman** [comment] 2020-05-19 13:44
I've been busy these days so I stopped looking at this, but off the top of my head:
-I used the sample app
-build tools to 29.0.3
-compile/target-sdk: 29
-android.core any higher than 1.1.0 (I had the problem using both 1.2.0 and 1.3.0-rc01)
-using PrecomputedFutureTextSetterCompat (commenting this resulted in everything ok)
-you have to change TextView to AppCompatTextView (as we designed in PrecomputedFutureTextSetterCompat)

tell me if you can reproduce it

**Comment by aggarwalpulkit596** [comment] 2020-05-19 15:11
> @aggarwalpulkit596 @KirkBushman ,
> 
> Changing compile and target SDK to `29` and build tools to `29.0.3` has no effect for me. Tables are rendered as expected both in a `RecyclerView` and not, with precomputed text setter or not. It seems to be an error somewhere else. Can you please provide an input that I can reproduce?
should I send you the markdown response? but i don't think so it would be of any help either as it's getting render afterwards

**Comment by aggarwalpulkit596** [comment] 2020-05-19 15:22
@noties take a look
![GIF-200519_204948](https://user-images.githubusercontent.com/29139786/82345137-87ffd280-9a12-11ea-8402-c7c7df5a742e.gif)

**Comment by noties** [comment] 2020-05-20 10:22
@aggarwalpulkit596 your issue is in the `ExpandableTextView`. Tables are initialized right away when markdown is applied to a `TextView`. As `ExpandableTextView` creates a smaller sub-sequence of full input it ignores tables. So `TableInvalidator` does not see any `TableRowSpan`s. Thus tables are not initialized properly and cannot invalidate `TextView` widget. 

Still, these 2 reports do seem to be connected as both seem to be caused by improper/missing table invalidation

**Comment by noties** [comment] 2020-06-09 15:02
Hello @KirkBushman , @aggarwalpulkit596 ,

I've been investigating this issue and come to conclusion that you should not use `PrecomputedFutureTextSetterCompat` **if** you markdown content has _dynamic_ content such as images, tables or latex. The reason is simple - dynamic content affects layout of text. Moreover it is calculated based on current `TextView` size. 

So `PrecomputedFutureTextSetterCompat` _precomputes_ dynamic content and leaves it in intermediate state. Normally it won't matter, as spans would recalculate sizes when first appear. But due to some internal doings of `AppCompatTextView` and `Future<PrecomputedTextCompat>` the very first invalidation of spans is ignored. This is why the first time span appears it appears in bad state. But further renders are OK. 

A possible fix is to not use `PrecomputedFutureTextSetterCompat`, but instead the `PrecomputedTextSetterCompat` which (strangely) works as expected and has full support for all content - static and dynamic.

Another possible fix is to create custom invalidators for all dynamic content. A quick test showed that if a `TableInvalidator` would use:

```java
// create a copy of current text
view.setText(new SpannedString(view.getText()));

// instead of this
// view.setText(view.getText());
```

But I'm not sure if doing this would still have any benefit at all (if not make things worse). Still, if you are determined to use `PrecomputedFutureTextSetterCompat` it might be an option also.

I'm closing this issue fro now as there is nothing `Markwon` can do. If you will have any ideas feel free to post them here and I will reopen it

**Closed by noties** 2020-06-09 15:02 UTC
Labels: :bug: bug
