### ISSUE TITLE
Number of issues

### ISSUE THREAD

**Issue by maciej-kaznowski** [noties/Markwon#16] opened 2017-11-20 20:48 UTC
Hi, first and foremost - thank you very much for this library, I'm really impressed with it so far.
I'm developing a reddit app and using the markdown in [this comment](https://www.reddit.com/r/reddit.com/comments/6ewgt/reddit_markdown_primer_or_how_do_you_do_all_that/c03nik6/) I have come accross the following issues, where the top part of the screen is what it should look like, and bottom part is what it looks like with this library:
1. [Superscripts are not supported](https://lh3.googleusercontent.com/SIR6r8Z9LExgEVbJ8lBhpu8jVK1HkObzI6UwR6SBnBFaXQsp2933Q2oSufPmtIXamAfm9uQNljT0Mvo_fXAQchQtGq6tQZQsVA0gdjtR9pJusGpjLK7OBi1CpVO2J739XRCm9Fsjx1IYvyvDp6SphMIADZCvMkZ5c1nuJ_mIuHJ3njQ6qlEzdxOPoMBa0Wt_x92seBN1elNmCqfo_zZqtY2Gklw5EwO8FRPwrEqxMBKJE6AqUIeQl9Mz4Ii5gTu6w1sqJCNhCUFna5S0rlQNJphaodxeuryilzIWEhmAQwSTjxMlk5XhBqjJJ42F_JvFthG8WwyLk3r0e3Q4YyjIYQyGYHd1uxN9x55YVeaYHmGUAwgyMsUzLO3LgFHyEMpkMNZEiAsAK2oZArnTlrXk9FiscFTfrFYRYGG95cwtk5ZkX0lHo6MG1XjBG4qSki0CQ6dTSIPgTftxWBqSlagCQKJRjBEHlRYi44OdIdRODoMdifGaLbb0EwHI7nb2qWTeD0qIO051hhTkGM9QkKt1PiUKEIs5GhWMWfznSxkGWQajgu6DgnlFL-0dScczsEM0xamuJSQ0NFq51_i2aWTWXqkO59HHdwg3mVKyAFvityRLnOEzk70xFDwUOxbuI1PuJksOT2h512MFNtBg12ABgK5LyFAlXWT5_eM=w442-h784-no)
2. ~~[Headers don't work when hashtag isn't followed with a space](https://lh3.googleusercontent.com/3zvAylDPPJpQAZu9_sUcXBb0tZiAu0Pjo2EfvY3X6PnMxqv5idqHxE4IpAH9IN_dbotRRLN4XVKCIh0gh1WJuH4otfeq317mVUYvthH2NigGKRNXl1P4spnuZhL6p0QY4Iz5FC7h-C1UB04r7Rc5nfHfYicr4KndvTkYLO6-2gEIEcc8ShbR-xnWOFnLWbyvwC8B575PnV7mn3NnFgAG_MQ0Z7nCnpiMxExqCjpBUgS0zX8Q3S464IncrFdqabSwKaOeptmHieBDaGpWTAdOGUhxSt34BLbDeivXLjiXCUkhBgd8dqL_Z7MLPwNkv3pnJ-lZDINzGnhq3i9ezXPjYcFrf2Wxsxq3Hy5G0KBers1lvHthYAYyxTrBeI_Jar6L9lhr7gxCOxFoaXdm1tsCxBjSvJZuxcsbNKvrx9zCLXxqRuCQGMbvrxgFndx_QcbuGF9HrYI-DeRuDqTRspO89Pb0D5AFY5xKfynBOhzn_bNuMzK466rzXNj2WpbzidZk1qQoS_5SWIWjw0hIgj5hQVa4Vnj9Y4tLdCabF6_adWRgEX13JpA82I-zf8ZjitN9SjwsdOHosXCxxCdzp-JWEufZTF13ATjvyfH61jNtYIGJLFxW2cK7rSfG6ABreMVCdlQYrwnUi-NptjQpHbeHKtPyVc_6Pz_SuGE=w442-h784-no)~~  working as intended according to [commonmark-java](https://github.com/atlassian/commonmark-java/blob/master/commonmark-test-util/src/main/resources/spec.txt#L792)
3. [Headers are underlined](https://photos.google.com/share/AF1QipPpkB0Tmg_ZtbnbPByl00s24CWoUm-K0PJT-5pKsGBG9iixmyaP5I-o4BAsXMosHA/photo/AF1QipMLKrHpu3Wjvra7-a_JkM-6n_MprBM0fM517u46?key=S1FDUkgyekNUdXdLeHZWclVCRGhvTDlJbl9SSGFn)
4. ~~[Ordered lists don't start from 1](https://lh3.googleusercontent.com/IYN_7uYKji9OGhIqMPsDmTqZixHUb7_icsaemIoVVypIjm_kRWT7eJriGIL13imZgEV8MfJgO_BgG3lB7e7-U-3QoQeb49anAYhBJtzmnFKXeHcRzLTHXcvmFCdBoMr9X4tpsrHum_A9RMcEyQM2oehtRPGMJzI7MMv9Liu9jpbVPlt5cGfFNe3_pMKPcGbKPu1FR2JSM-Ebw7bQF6tD1xUPl5E7z9WTvf8dLLaeGLpwcOVcBw8ynJsCU7h8UVmmk4yV9BAPAsjuCFeOR7MQzXwurzjhvAtkG73KVwnIxUNLfYuWCYR_QHhdyx_4TjGbuaez2adltWwVy24bFz2MiC_kDVQgpqkHd0EMxAjv5CDVzgY9i_U5ByE_jD54FZxF-czJE_apzrWLSpVYS7ekGCFEQlOJ1S16BrjvmFz33FZMohNSiXwrlhomuDmSNmAXZiMh843JnWc7lantY3g2q0QAkxyDt4V3ZUyiuLOoPrlQGRPfDabaNWsyn0xWltzY8IqO3ZAO2zhTs2eQYDrSE_w0C05wb2ZwEdljIULJzVgEcZXQMz1I2EV8BUUVRpfLFol-tVFc_i6LTzJ725ku6_8sl4cUdjjR_5YtvYqCPuAzXoHZCR6W4oIjirec5ObydSN1x2tbdSwh1YjR8JL87tkZxr_2frrsmxQ=w442-h784-no)~~ working as intended according to [commonmark-java](https://github.com/atlassian/commonmark-java/blob/master/commonmark-test-util/src/main/resources/spec.txt#L4795)
5. [Code blocks don't work](https://lh3.googleusercontent.com/K3b52FR2_Xzxk5fNivj-aA8FhWi-JkyPANxF7Zi6t7wI7Crg79ar5qpZHpUMGsJYDunKFcIWL5uRZ_u9OBt4qH4xYTkZST3Ng4e3me37O495RhkTHguJyx5PDv__xvlLFTTL4fLpMpSY7orQW5o3mkucR7-M2lDbbvKKBsTGtNfZhvHGMAO_Csf1Z7aLyTD-iBVaurmlyoVhmjsCwaF8cGfkXkBzPP6jMq6Cd7ZlPhcyxwLT4LoO6c-F7GW7gvxUIfLOgFdb2PS-4vi3vSGR7g2bWKn-QRwRmT4SIpPl8vvJb8RA6EEGmpgynJB0K_B19i9DyPVnEIdueD1I6YAeAQ4V0I0vBh20xvzx9xPM5tqb5IAOxA5KU20zr8zUi87x1GpUECVXW-fI7wK8Z9RFUpU45JT5-2aVdSzBc6SSXb1_e2TP0TMfzWpHCCW9vWGVUM4qgI6qAa8zAuU6vDF4ZXpRtMhYgUyyBeGRcP44vRHhcO9mNvFTihHsrpagwM3iOEkcRSiiSWcFI7D53pWiPRORb2E9-DXGRDbm9NDLqn_DuXt8mSun5bu6A254i6Y5vqepf8Fw7JawwzabwehBbzd_bOa0kJ2DCcsvR14sOzBdz8HZdqnflb573hrYLhKnRooulgZ4v0QYDWW-JUUy7LkwX580zBSidNE=w442-h784-no)

2  Might not follow the markdown spec but I'm not sure.

I also can't use Markwon.scheduleTableRows(textView) as I'm using a custom view to draw the text.  Looking at the source, it shouldn't be too hard I think to implement  this, as all it would need would be to provide an interface with setText and getText methods

**Comment by noties** [comment] 2017-11-21 10:46
Hey @maciej-kaznowski !

First of all, let me clarify: this library uses: [commonmark-java](https://github.com/atlassian/commonmark-java) for parsing markdown (which is based on [commonmark](http://commonmark.org) specification). You can try it yourself [online](http://spec.commonmark.org/dingus).

(I see, that you are updating your issue, but anyway)

1. There is no support for such superscript functionality currently in the spec. Even github refuses to accept it: ^super. This could be addressed, if for example superscript was represented by delimiter `^` at start and end, so a simple extension could be made. Anyway you can use `<sup></sup>` HTML tag if it's applicable.

2. Yeah, headers must have a space.

3. __Agreed__. Although there is an option to specify header underline height (for level 1 & 2), it's not working as intended: `SpannableTheme.builderWithDefaults(context).headingBreakHeight(0).build()` would still draw an underline.

4. Please do not start holy war here, I know it's not arrays, but still.

5. Multiline code blocks _are_ supported. Use 3 backticks (<b>&#96;&#96;&#96;</b>). It's in commonmark spec too.

```java
System.out.println("Hello commonmark!");
```

Depending the scheduling: although it's not a bad idea to introduce an abstraction for text invalidation, I still think that it sounds like rare case for general usage. Please take a look at `TableRowsScheduler`, it doesn't use any private API, so you can mimic it's behaviour to answer your needs.

**Comment by noties** [comment] 2017-11-24 09:12
I'm closing this as the issue with headers underline is resolved in `1.0.2` release. (Others are just reddit specifics on markdown spec)

**Closed by noties** 2017-11-24 09:12 UTC
